### PR TITLE
when parts == [] , just Exit

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by CharlesOkwuagwu** [comment]
Seems the checks only fail for OTP 19.6 but pass for OTP 20. Could it be a configuration issue?

**Comment by CrowdHailer** [comment]
Looks good to me.

can you rebase of the latest master commit. That should fix the tests, but best to double check.

**Comment by CharlesOkwuagwu** [comment]
I edited master directly on GitHub ... so should be up-to-date

**Comment by CrowdHailer** [comment]
I changed master a few minutes ago

**Comment by CrowdHailer** [comment]
If you check network you can see where you branched from https://github.com/CrowdHailer/Ace/network

**Pull request closed without merging**
