### PR TITLE
Add h2spec exunit

### PR DESCRIPTION
**Pull request by varnerac**
Ignore the initial commit. I was working off an earlier branch that fixed the unknown frame. I just want to post this as an idea for how to bring H2Spec into the tests.

What do you think about this to bring H2Spec into the test infrastructure? It looks to see if the archive (tar.gz) of the right version is present in the `test/support` directory. If not, it pulls the right version for your OS from the GitHub releases page and decompresses it. I then run the H2Spec test suite as a single ExUnit test.

Alternative solutions could include just bundling h2spec (Linux, Mac and Windows versions) in the test support directory.

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Is this PR mean to include the file in test/support?

I like the look of this approach. I don't mind pulling it in CI. we still have the ability to run just elixir tests for local development

**Comment by varnerac** [comment]
Well, this would pull/run h2spec in local development too. You can override it with an environment variable. If h2spec is on your `$PATH`, it doesn’t pull one.

**Comment by varnerac** [comment]
Also, I need to clean this up with some docs and other stuff if you are okay with the approach.

**Comment by CrowdHailer** [comment]
I'm good with the approach.

Could you add a doctag so `mix text --ci` or something similar included these tests. but normal mix test didnt?

**Comment by varnerac** [comment]
Cleaned up a little. I exclude the `:ci` tag in the test setup, and show how to run it in CI.

**Comment by varnerac** [comment]
Bump

**Comment by CrowdHailer** [comment]
We could add running these test's to travis?

**Comment by varnerac** [comment]
Yes. I'll PR it.

**Pull request merged**
