### PR TITLE
Bump Raxx and add tests

### PR DESCRIPTION
**Pull request by varnerac**
Bumps Raxx to 0.15.1 and adds tests around raw_path.

### CODE REVIEW

**Comment by CrowdHailer** [comment]
@varnerac why have you deleted the `mix.lock` file? 
Otherwise all makes sense to me. tests look a good addition

**Comment by varnerac** [comment]
Oversight on my part. I’ll fix and push

**Comment by CrowdHailer** [comment]
This also needs an entry in the CHANGELOG

**Comment by CrowdHailer** [comment]
Thanks :whale:

**Pull request merged**
