### PR TITLE
Add some naming to the Supervisors

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**
Adding names to the Supervisors gives us a better visual representation in `:observer` that's easier to understand at a glance.

screen

### CODE REVIEW

**Comment by CrowdHailer** [comment]
A nice though but needs a bit more to make it work. You can see the problem from the test failures on travis https://travis-ci.org/CrowdHailer/Ace/jobs/300911691#L613

**Comment by CharlesOkwuagwu** [comment]
Noted, but we only ever have one instance of these three supervisors running at a time, hence I felt they could be named just once, and their names reused

**Comment by CrowdHailer** [comment]
You might well have multiple running in production at the same time. On the chat in `elixir-on-docker` There are two service trees, one for HTTP and one for HTTPS each of which has an endpoint supervisor etc.

**Comment by CrowdHailer** [comment]
@CharlesOkwuagwu do you want to solve this so that names are based off of the top service name or should I close this PR?

**Comment by CharlesOkwuagwu** [comment]
It's non critical you can close this. Will reopen-if i get round to making a PR for the naming.

**Pull request closed without merging**
